AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Parameters:
  RoleARN:
    Type: String

Resources:


  retrieveSolarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: source/retrieve_solar_viability/
      FunctionName: !Sub "retrieve_solar_viability-${AWS::StackName}"
      Handler: retrieve_solar_viability.lambda_handler
      Role: !Ref RoleARN
      Runtime: python3.9
      Timeout: 300
      # VpcConfig:
      #   SubnetIds: !Ref LambdaSubnets
      #   SecurityGroupIds:
      #     - !Ref PAVMLifecycleHookLambdaSecurityGroup
